# Generated by Django 6.0.5 on 2026-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=128, unique=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('city', models.CharField(blank=True, db_index=True, max_length=128)),
                ('visits', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
